version: '3.9'
services:
  app:
    container_name: check-mate
    environment:
      - LISTEN_ADDR=8080
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - SSL_MODE=disable
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    ports:
      - '5432:5432'