version: '3.9'
services:
  app:
    container_name: check-mate
    environment:
      - PORT=8080
      - DB=host=postgresdb port=5432 user=postgres password=postgres dbname=postgres sslmode=disable
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'